### ISSUE TITLE
When "sorting by date" in channel video overwiew is changed, the video upload date doesn't change aswell

### ISSUE THREAD

**Issue by 0rsch** [RandomGamingDev/yt-times#5]
First of all: no YT add-on right now is able to show the exact date of a video. So thanks for your work with this add-on.
One issue: when going to a YT channel, section "Videos", all videos of a channel get listed in the order of newest to oldest.

By changing the sorting to "oldest to newst" or "most viewed/popular", the information of the date won't be updated.
The shown dates are in order as they were in the sorting "newest to oldest" before.

**Comment by Omni-Consumer-Products** [comment]
Adding some screenshots RandomGamingDev requested for this issue here: https://addons.mozilla.org/en-US/firefox/addon/youtube-times/reviews/2139676/

What you get when clicking on the "Videos" for a channel:

![Image](https://github.com/user-attachments/assets/752c273b-cb4c-4fde-bc99-630f79048b85)

What you get after clicking "Popular" on that same page - note the videos have changed, but the timestamps have not:

![Image](https://github.com/user-attachments/assets/a831f691-09c7-4480-b91b-71c5fd7397ec)

Thank you for developing this extension!   I can't stand relative times!

**Comment by RandomGamingDev** [comment]
> First of all: no YT add-on right now is able to show the exact date of a video. So thanks for your work with this add-on. One issue: when going to a YT channel, section "Videos", all videos of a channel get listed in the order of newest to oldest.
> 
> By changing the sorting to "oldest to newst" or "most viewed/popular", the information of the date won't be updated. The shown dates are in order as they were in the sorting "newest to oldest" before.

Sorry about the late response @0rsch, and thanks for the example @Omni-Consumer-Products (great usage of the rickroll lol). I'll make sure to get to the issue soon.

**Comment by RandomGamingDev** [comment]
@0rsch @Omni-Consumer-Products 
This issue has been fixed in version 1.0.5 and this issue will be closed. If there are any further issues just ping me :D

**Comment by 0rsch** [comment]
Hi @RandomGamingDev, it seems like the 1.0.5 isn't changing anything in this matter. It's still the same behaviour. I even tried the rickroll channel xD

Edit: Tried few other channels. Some work, some wont. The Rick Astley one doesn't seem to work.

**Comment by RandomGamingDev** [comment]
> Hi [@RandomGamingDev](https://github.com/RandomGamingDev), it seems like the 1.0.5 isn't changing anything in this matter. It's still the same behaviour. I even tried the rickroll channel xD
> 
> Edit: Tried few other channels. Some work, some wont. The Rick Astley one doesn't seem to work.

That's odd. It wasn't that way on my end. I'm a bit busy as of now, and would appreciate some pointers, but I'll make sure to check it myself when I can as well.
